version: '3.9'

services:

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - http.port=9200
    ports:
      - '9200:9200'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 5s
      timeout: 5s
      retries: 25

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:2375:2375'
    environment:
      - LOG_LEVEL=warning # debug,info,notice,warning,err,crit,alert,emerg
      - CONTAINERS=1
      - INFO=1

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    restart: always
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8125:8125/udp'
    depends_on:
      socket-proxy:
        condition: service_started
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=qwerty123qwerty123
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=qwerty123qwerty123
    ports:
      - '8086:8086'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8086/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana-oss
    container_name: grafana-server
    restart: always
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel
    ports:
      - '3000:3000'
    depends_on:
      influxdb:
        condition: service_healthy
      telegraf:
        condition: service_started

  siege:
    image: jstarcher/siege
    container_name: siege
    depends_on:
      - nginx
    command: -c 10 -t 30m http://nginx:8080/root/xor/random
