{
 "title": "Application Business Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "root-service cache latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": "lookup ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "lookup" }
     ]
    },
    {
     "alias": "update ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "update" }
     ]
    }
   ]
  },
  {
   "title": "xor-service cache latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "alias": "lookup ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "lookup" }
     ]
    },
    {
     "alias": "update ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "update" }
     ]
    }
   ]
  },
  {
   "title": "root-service cache hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 5 },
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "hits" }
     ]
    },
    {
     "alias": "mises",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "mises" }
     ]
    }
   ]
  },
  {
   "title": "xor-service cache hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "hits" }
     ]
    },
    {
     "alias": "mises",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" },
      { "condition": "AND", "key": "cache", "operator": "=", "value": "mises" }
     ]
    }
   ]
  },
  {
   "title": "API mean RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "root-service method invocations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" }
     ]
    }
   ]
  },
  {
   "title": "xor-service method invocations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "count",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" }
     ]
    }
   ]
  },
  {
   "title": "root-service method latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "time",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "root-service" }
     ]
    }
   ]
  },
  {
   "title": "xor-service method latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "time",
     "query": "SELECT sum(\"value\") FROM \"count\" WHERE (\"application\" = 'root-service' AND \"cache\" = 'hits') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "100_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "xor-service" }
     ]
    }
   ]
  }
 ]
}