quarkus:
  redis:
    hosts: redis://localhost:6379
    max-pool-size: 10
    max-pool-waiting: 11
#    ,redis://localhost:26380,redis://localhost:26381
#    client-type: sentinel
#    sentinel:
#      master-name: mymaster
    timeout: 10000
  vertx:
    worker-pool-size: 128
    event-loops-pool-size: 128
  http:
    io-threads: 128
  log:
    category:
      io.quarkus:
        level: INFO

app:
  entity-count: 50000
  prepopulate-percentage: 75
  generation-delay: 100ms
