quarkus:
  redis:
    hosts: redis://localhost:6379
#    ,redis://localhost:26380,redis://localhost:26381
#    client-type: sentinel
#    sentinel:
#      master-name: mymaster
#    timeout: 10000
  log:
    category:
      io.quarkus:
        level: INFO

app:
  entity-count: 1000
  prepopulate-percentage: 75
